spring:
  application:
    name: help-desk-api
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    showsql: true
    properties:
      hibernate:
        format_sql: true

